project:
  type: website
  output-dir: ../docs

bibliography: references.bib

website:
  title: "Yuken Ohshiro"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: News
        href: news/news.qmd
      - text: CV
        href: cv/cv.qmd
      - text: Research
        href: research/research.qmd
      - text: Publications
        href: publications/publications.qmd
      - text: Software
        href: software/software.qmd

format:
  html:
    theme:
      light: lux
      dark: slate
    fontsize: 1.1em
    linestretch: 1.3
    toc: true
    number-sections: false